name: Flutter CI
on:
pull_request:
branches: [ main, develop, feat/** ]
push:
branches: [ feat/** ]
jobs:
build-test:
runs-on: macos-14
steps:
- uses: actions/checkout@v4
- uses: subosito/flutter-action@v2
with:
channel: 'stable'
- run: flutter pub get
- run: flutter analyze
- run: flutter test